version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.8

    working_directory: /go/src/github.com/na1s/mfa

    environment:
      #TEST_RESULTS: /tmp/test-results

    steps:
      - checkout
      - run: mkdir -p $TEST_RESULTS

      - restore_cache:
          keys:
            - v1-pkg-cache

      - run: go get -u -v -t github.com/Masterminds/glide
      - run: glide install -v
      - run: go build -v github.com/na1s/mfa